server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: 'health,info'

springdoc:
  swagger-ui:
    disable-swagger-default-url: 'true'
    path: '/swagger-ui'

model-storage:
  host: http://arachni-storage-controller-develop.apps.os-lab-3.neo/api
  getModelUrl: ${model-storage.host}/models/
  modelName: model
